export const COMPARE_USER_BRACKET_REQUEST = 'COMPARE_USER_BRACKET_REQUEST'
export const COMPARE_USER_BRACKET_SUCCESS = 'COMPARE_USER_BRACKET_SUCCESS'
export const COMPARE_USER_BRACKET_ERROR = 'COMPARE_USER_BRACKET_ERROR'
